import { chromium } from 'playwright';
import { readFile, mkdir, writeFile } from 'node:fs/promises';
import assert from 'node:assert/strict';
import { installRedesignBrowser, authenticateRedesign } from '../../e2e/redesign-fixtures/browser.mjs';
const root = process.argv[2], output = process.argv[3];
const receipt = JSON.parse(await readFile(`${root}/process.json`, 'utf8'));
await mkdir(output, { recursive: true });
const browser = await chromium.launch({ headless: true });
const context = await browser.newContext({ viewport: { width: 1440, height: 1000 }, serviceWorkers: 'block' });
await authenticateRedesign(context, root);
const page = await context.newPage();
const guard = await installRedesignBrowser(page, { baseUrl: receipt.url, runtimeReceipt: receipt });
const errors = [], api = [];
page.on('pageerror', error => errors.push(error.message));
page.on('response', response => { if (response.url().endsWith('/api/admin/quota/scenario')) api.push({ status: response.status(), operation: response.request().postDataJSON()?.operation }); });
const rangeEnd = new Date().toISOString();
await page.goto(`${receipt.url}/dashboard?period=custom&start=${encodeURIComponent(new Date(Date.parse(rangeEnd) - 3600000).toISOString())}&end=${encodeURIComponent(rangeEnd)}`, { waitUntil: 'networkidle' });
await page.locator('[data-account-id="capacity-fixture-a"]').getByRole('button', { name: 'Details', exact: true }).click();
await page.getByRole('tab', { name: /Quota windows/ }).click();
const fleet = page.getByRole('region', { name: 'Fleet scenario', exact: true });
await fleet.waitFor();
await page.getByLabel('Fleet model', { exact: true }).fill('cx/gpt-5.2');
const waitComparison = () => page.waitForResponse(response => response.url().endsWith('/api/admin/quota/scenario') && response.request().postDataJSON()?.operation === 'compare');
let pending = waitComparison();
await page.getByRole('button', { name: 'Capture fleet', exact: true }).click();
let response = await pending;
assert.equal(response.status(), 200);
let comparison = await response.json();
assert.equal(comparison.baseline.connectionId, 'capacity-fixture-a');
const general = comparison.accounts[0].products.find(product => product.id === 'general');
assert.equal(general.windows.length, 3);
assert.equal(comparison.accounts[0].products.find(product => product.id === 'spark').windows.length, 3);
assert.equal(general.windows[0].adjusted.state, 'reset_before_exhaustion');
await page.getByLabel('Demand multiplier', { exact: true }).fill('2');
await page.getByLabel('Demand multiplier', { exact: true }).press('Tab');
await page.getByLabel('Projection hours', { exact: true }).fill('6');
pending = waitComparison();
await page.getByRole('button', { name: 'Compare captured fleet', exact: true }).click();
comparison = await (await pending).json();
assert.equal(comparison.scenario.multiplier, 2);
assert.equal(comparison.projectionPeriod.hours, 6);
const originalCapture = comparison.captureId;
const record = general.windows[0].contributingRecords[0];
const evidence = await context.request.get(`${receipt.url}${record.href}`);
assert.equal(evidence.status(), 200);
const evidenceBody = await evidence.json();
assert.equal(evidenceBody.total, 1);
assert.equal(evidenceBody.items[0].id, record.id);
await page.reload({ waitUntil: 'networkidle' });
const inspectorReopenedAfterReload = !await page.getByRole('tab', { name: /Quota windows/ }).count();
if (inspectorReopenedAfterReload) await page.locator('[data-account-id="capacity-fixture-a"]').getByRole('button', { name: 'Details', exact: true }).click();
await page.getByRole('tab', { name: /Quota windows/ }).click();
await page.getByLabel('Demand multiplier', { exact: true }).waitFor();
assert.match(await page.getByLabel('Demand multiplier', { exact: true }).inputValue(), /^2/);
assert.equal(await page.getByLabel('Projection hours', { exact: true }).inputValue(), '6');
assert.ok((await fleet.textContent()).includes(originalCapture));
for (const [width, height] of [[1440, 1000], [1920, 1080], [390, 1000]]) {
  await page.setViewportSize({ width, height });
  await fleet.evaluate(element => element.scrollIntoView({ block: 'start' }));
  await page.screenshot({ path: `${output}/fleet-${width}x${height}.png` });
  await fleet.getByRole('group', { name: 'capacity-fixture-a General product', exact: true }).evaluate(element => element.scrollIntoView({ block: 'start' }));
  await page.screenshot({ path: `${output}/fleet-products-${width}x${height}.png` });
  assert.ok(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth + 1), `page overflow at ${width}`);
  assert.ok(await fleet.evaluate(element => element.scrollWidth <= element.clientWidth + 1), `fleet overflow at ${width}`);
}
await page.getByRole('combobox', { name: 'Unavailable accounts', exact: true }).fill('capacity-fixture-a');
await page.getByRole('option', { name: 'capacity-fixture-a', exact: true }).click();
pending = waitComparison();
await page.getByRole('button', { name: 'Compare captured fleet', exact: true }).click();
comparison = await (await pending).json();
assert.equal(comparison.changed.connectionId, null);
assert.equal(comparison.accounts[0].available, false);
const failRoute = route => route.fulfill({ status: 503, contentType: 'application/json', body: JSON.stringify({ error: 'Controlled evidence read failure' }) });
await page.route('**/api/admin/quota/scenario', failRoute);
await page.getByRole('button', { name: 'Compare captured fleet', exact: true }).click();
await page.getByText('Controlled evidence read failure', { exact: true }).waitFor();
assert.equal(await page.locator('[aria-label="Fleet comparison"]').count(), 0);
await page.screenshot({ path: `${output}/fleet-failure-390.png` });
await page.unroute('**/api/admin/quota/scenario', failRoute);
pending = waitComparison();
await page.getByRole('button', { name: 'Compare captured fleet', exact: true }).click();
assert.equal((await pending).status(), 200);
assert.deepEqual(errors, []);
assert.deepEqual(guard.outboundFailures, []);
const proof = { synthetic: true, source: 'retained synthetic-fleet-proof observations through real local APIs', root, url: receipt.url,
  viewports: ['1440x1000', '1920x1080', '390x1000'], restoredCaptureId: originalCapture, recordsLinked: evidenceBody.total,
  demand: 2, projectionHours: 6, exclusionApplied: true, reloadRestored: true, inspectorReopenedAfterReload, keyboard: 'Tab after editing demand', failureClearsResult: true,
  recoverySucceeded: true, pageErrors: errors, outboundFailures: guard.outboundFailures, api, providerCalls: 0 };
await writeFile(`${output}/browser-evidence.json`, JSON.stringify(proof, null, 2));
console.log(JSON.stringify(proof));
await browser.close();
