// The wire permission belongs to the attempt that produced this response.
// Absence is deliberately false because transport and parse failures can occur
// after an accepted, billable request even when their local status is 502.
export function withReplaySafety(response, safeToReplay = false, retryAfterMs = 0, clientRetrySafe = safeToReplay) {
  const headers = new Headers(response.headers);
  headers.set('x-tokenproxy-replay-safe', String(safeToReplay === true));
  // Stainless-based clients honor this even for 429/5xx. An uncertain attempt
  // must not be regenerated by the client after the gateway refuses replay.
  if (clientRetrySafe !== true) headers.set('x-should-retry', 'false');
  else if (!safeToReplay && !headers.has('x-should-retry')) headers.set('x-should-retry', 'true');
  if (Number.isFinite(retryAfterMs) && retryAfterMs > 0 && !headers.has('retry-after')) headers.set('retry-after', String(Math.max(1, Math.ceil(retryAfterMs / 1000))));
  return new Response(response.body, { status: response.status, statusText: response.statusText, headers });
}
const REJECTED_STATUSES = new Set([400, 401, 402, 403, 404, 405, 413, 415, 422, 429]);

// Use at an actual upstream response boundary. An adapter that turns an
// accepted response or exposed output into an error must carry an explicit
// false permission. A 5xx status alone says nothing about paid acceptance.
export function isReplaySafeRejection(response, payload) {
  if (!response || response.status < 400 || response.status >= 600) return false;
  const permission = response.headers?.get?.('x-tokenproxy-replay-safe');
  if (permission === 'false' || response.headers?.get?.('x-should-retry') === 'false') return false;
  if (response.status === 429) return isSafeQuotaAccountRejection(response, payload);
  return permission === 'true' || REJECTED_STATUSES.has(response.status);
}

// An account-specific retry prohibition is distinct from accepted generation.
// Only a complete parsed canonical 429 envelope can make that distinction.
export function isSafeQuotaAccountRejection(response, payload) {
  if (response?.status !== 429 || response.headers?.get?.('x-tokenproxy-replay-safe') === 'false') return false;
  if (!payload || typeof payload !== 'object' || Array.isArray(payload)) return false;
  if (Object.keys(payload).some(key => !['error', 'type', 'request_id', 'requestId'].includes(key))) return false;
  if (!payload.error || typeof payload.error !== 'object' || Array.isArray(payload.error)
      || typeof payload.error.message !== 'string' || !payload.error.message.trim()) return false;
  // Known scalar error envelopes only. Arbitrary nested metadata cannot prove
  // rejection, and a string reporting accepted work overrides HTTP 429.
  if (Object.keys(payload.error).some(key => !['message', 'type', 'code', 'param', 'status'].includes(key))) return false;
  const generationEvidence = /(?:^|[\W_])(?:accept(?:ed|ance)?|generat(?:ed|ing|ion)|bill(?:ed|able)|charg(?:ed|es|ing)|tool[\W_]+(?:call|result)|(?:request|prompt)[\W_]+(?:was[\W_]+)?(?:processed|completed)|(?:partial|produced|emitted)[\W_]+(?:content|output)|usage[\W_]+(?:reported|recorded|incurred))(?:$|[\W_])/i;
  for (const value of [...Object.entries(payload).filter(([key]) => key !== 'error').map(([, value]) => value), ...Object.values(payload.error)]) {
    if (value != null && !['string', 'number'].includes(typeof value)) return false;
    if (typeof value === 'number' && !Number.isFinite(value)) return false;
    if (typeof value === 'string' && generationEvidence.test(value)) return false;
  }
  return true;
}
