// The wire permission belongs to the attempt that produced this response.
// Absence is deliberately false because transport and parse failures can occur
// after an accepted, billable request even when their local status is 502.
export function withReplaySafety(response, safeToReplay = false, retryAfterMs = 0, clientRetrySafe = safeToReplay) {
  const headers = new Headers(response.headers);
  headers.set('x-tokenproxy-replay-safe', String(safeToReplay === true));
  // Stainless-based clients honor this even for 429/5xx. An uncertain attempt
  // must not be regenerated by the client after the gateway refuses replay.
  if (clientRetrySafe !== true) headers.set('x-should-retry', 'false');
  else if (!safeToReplay && !headers.has('x-should-retry')) headers.set('x-should-retry', 'true');
  if (Number.isFinite(retryAfterMs) && retryAfterMs > 0 && !headers.has('retry-after')) headers.set('retry-after', String(Math.max(1, Math.ceil(retryAfterMs / 1000))));
  return new Response(response.body, { status: response.status, statusText: response.statusText, headers });
}
