// Exact transitive local-import closure of the analytics Worker entrypoint.
// The worker is loaded by path at runtime, so Next traces nothing it imports and
// every file here must be listed for the standalone output to be able to start
// it. A glob is what broke it: `analytics/*.mjs` shipped the worker and its
// query modules but not the sibling .js schema files they import, so the worker
// died on ERR_MODULE_NOT_FOUND for economicsProjectionSchema.js before its first
// message and /api/analytics answered 503. Same convention as
// SHAPING_WORKER_FILES and COMPATIBILITY_WORKER_FILES.
//
// Regenerate after changing an analytics import, then rebuild:
//   node scripts/analytics-worker-closure.mjs --check
export const ANALYTICS_WORKER_FILES = [
  "./open-sse/translator/formats.js",
  "./open-sse/utils/replaySafety.js",
  "./src/lib/compatibility/evidence.mjs",
  "./src/lib/compatibility/model.mjs",
  "./src/lib/dataDir.js",
  "./src/lib/db/accessProfileSchema.js",
  "./src/lib/db/adapters/betterSqliteAdapter.js",
  "./src/lib/db/adapters/bunSqliteAdapter.js",
  "./src/lib/db/adapters/criticalAckJournal.js",
  "./src/lib/db/adapters/criticalTransaction.js",
  "./src/lib/db/adapters/nodeSqliteAdapter.js",
  "./src/lib/db/adapters/sqljsAdapter.js",
  "./src/lib/db/adapters/writerAdmission.js",
  "./src/lib/db/analytics/activityQueries.mjs",
  "./src/lib/db/analytics/contextEvents.mjs",
  "./src/lib/db/analytics/contextEvidenceExport.mjs",
  "./src/lib/db/analytics/contextQueries.mjs",
  "./src/lib/db/analytics/contextRelated.mjs",
  "./src/lib/db/analytics/contextStructure.mjs",
  "./src/lib/db/analytics/counterfactualEvidence.mjs",
  "./src/lib/db/analytics/diagnostics.mjs",
  "./src/lib/db/analytics/economicsDimensions.mjs",
  "./src/lib/db/analytics/economicsLinks.mjs",
  "./src/lib/db/analytics/evidenceFormat.mjs",
  "./src/lib/db/analytics/evidenceQueries.mjs",
  "./src/lib/db/analytics/investigationModel.mjs",
  "./src/lib/db/analytics/keyUsageQueries.mjs",
  "./src/lib/db/analytics/notificationRuleQueries.mjs",
  "./src/lib/db/analytics/operationEventsQueries.mjs",
  "./src/lib/db/analytics/quotaHistoryQueries.mjs",
  "./src/lib/db/analytics/quotaReplenishment.mjs",
  "./src/lib/db/analytics/quotaTrend.mjs",
  "./src/lib/db/analytics/quotaWorkbenchQueries.mjs",
  "./src/lib/db/analytics/readOnly.mjs",
  "./src/lib/db/analytics/sessionPinTimelineQueries.mjs",
  "./src/lib/db/analytics/telemetryFilter.mjs",
  "./src/lib/db/analytics/worker.mjs",
  "./src/lib/db/backup.js",
  "./src/lib/db/budgetSchema.js",
  "./src/lib/db/compatibilitySchema.js",
  "./src/lib/db/completionIdentity.mjs",
  "./src/lib/db/configVersionSchema.js",
  "./src/lib/db/contextEvidenceSchema.js",
  "./src/lib/db/contextStageOutcomeSchema.js",
  "./src/lib/db/costLedgerSchema.js",
  "./src/lib/db/criticalAckSchema.js",
  "./src/lib/db/driver.js",
  "./src/lib/db/economicsProjectionSchema.js",
  "./src/lib/db/helpers/metaStore.js",
  "./src/lib/db/helpers/secretCol.js",
  "./src/lib/db/investigationSchema.js",
  "./src/lib/db/keyRotationSchema.js",
  "./src/lib/db/migrate.js",
  "./src/lib/db/migrations/001-initial.js",
  "./src/lib/db/migrations/002-compatibility-scopes.js",
  "./src/lib/db/migrations/003-connection-identity.js",
  "./src/lib/db/migrations/004-economics-projection.js",
  "./src/lib/db/migrations/005-economics-token-affinity.js",
  "./src/lib/db/migrations/006-economics-visibility.js",
  "./src/lib/db/migrations/007-economics-cache-presence.js",
  "./src/lib/db/migrations/index.js",
  "./src/lib/db/notificationAutomationSchema.js",
  "./src/lib/db/notificationDeliverySchema.js",
  "./src/lib/db/notificationRuleSchema.js",
  "./src/lib/db/operationSchema.js",
  "./src/lib/db/paths.js",
  "./src/lib/db/projectSchema.js",
  "./src/lib/db/replayEvidence.js",
  "./src/lib/db/schema.js",
  "./src/lib/db/schema/quotaHistory.js",
  "./src/lib/db/sessionPinSchema.js",
  "./src/lib/db/shapingSchema.js",
  "./src/lib/db/telemetryOutcomeSchema.js",
  "./src/lib/db/terminalEvidence.js",
  "./src/lib/db/version.js",
  "./src/lib/notifications/conditions.mjs",
  "./src/lib/shutdown.js",
];
